# Generated by Django 4.0.3 on 2022-03-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='slug',
        ),
    ]
