# Generated by Django 4.0.3 on 2022-03-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_options_rename_usuario_pedido_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nome'),
        ),
    ]
