# Generated by Django 4.0.3 on 2022-04-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_remove_pedido_id_alter_pedido_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagem',
            field=models.ImageField(default='static/brocolis.jpeg', upload_to='', verbose_name='Imagem'),
        ),
    ]
