# Generated by Django 4.0.3 on 2022-04-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_pedido_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='imagem',
            field=models.ImageField(upload_to='media', verbose_name='Imagem'),
        ),
    ]
